import Layout from "@/components /layout";
import { POSTS } from "@/data/posts";
import { Post } from "@/interfaces/post.interface";
import Head from "next/head";
import Link from "next/link";

export async function getStaticProps({ params }: { params: { id: string } }) {
  const posts: Post[] = POSTS;
  return {
    props: {
      posts,
    },
  };
}

export default function List({ posts }: { posts: Post[] }) {
  return (
    <Layout>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center">
        {posts.map((post) => (
          <Link key={post.title} href={post.id} className="underline">
            {post.title}
          </Link>
        ))}
      </div>
    </Layout>
  );
}
