import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <p className="text-center font-bold">Bienvenidos a mi blog</p>
        <Link href="/post/list" className="underline">
          <p className="text-center">Artículos</p>
        </Link>
      </section>
    </>
  );
}
