import { POSTS } from "@/data/posts";
import Head from "next/head";
import { Post } from "../../interfaces/post.interface";
import Image from "next/image";
import Layout from "@/components /layout";
import Link from "next/link";

export async function getStaticPaths() {
  const paths = POSTS.map((post) => {
    return {
      params: {
        id: post.id,
      },
    };
  });
  return { paths: paths, fallback: false };
}

export async function getStaticProps({ params }: { params: { id: string } }) {
  const postData: Post = POSTS.find((post) => post.id === params.id)!;
  return {
    props: {
      postData,
    },
  };
}

export default function PostData({ postData }: { postData: Post }) {
  return (
    <Layout>
      <Head>
        <title>{postData.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/post/list" className="underline">
          Posts
        </Link>
        <div className="w-full h-[32rem]">
          <Image
            className="mx-auto object-scale-down"
            src={postData.image}
            alt={postData.title}
            width={500}
            height={500}
          ></Image>
        </div>
        <p className="text-center">{postData.content}</p>
      </div>
    </Layout>
  );
}
